// <auto-generated />
namespace ArtisansBeadStudio.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class Styles : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Styles));
        
        string IMigrationMetadata.Id
        {
            get { return "202308031923169_Styles"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
